# Generated by Django 4.2.2 on 2024-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='quality_check_status',
            field=models.CharField(choices=[('not_inspected', 'Not Inspected'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_inspected', max_length=20),
        ),
    ]
