# Generated by Django 4.2.2 on 2023-09-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='column_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='row_column_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
