# Generated by Django 4.2.2 on 2023-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapp', '0002_stock_column_end_stock_row_column_start_stock_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='row_column_start',
            new_name='column_start',
        ),
        migrations.AddField(
            model_name='stock',
            name='row_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
