# Generated by Django 4.2.2 on 2023-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapp', '0003_rename_row_column_start_stock_column_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='remaining_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
