# Generated by Django 4.2.2 on 2023-10-01 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0013_orders_delivered_at'),
        ('controllerapp', '0004_stock_is_active_stock_remaining_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_address', models.TextField()),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_contact_info', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.product')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllerapp.stock')),
            ],
        ),
    ]
