# Generated by Django 4.2.2 on 2023-10-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0013_orders_delivered_at'),
        ('controllerapp', '0006_alter_stock_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.orders'),
        ),
    ]
