# Generated by Django 4.2.2 on 2023-10-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0014_orders_buying_price_orders_total_price'),
        ('controllerapp', '0009_sales_profit_sales_total_buying_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='USERAPP.orders'),
        ),
    ]
