# Generated by Django 4.2.2 on 2023-09-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0003_alter_orders_order_status_alter_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
