# Generated by Django 4.2.2 on 2023-09-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0006_storagelocation_orders_is_stored_productlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlocation',
            name='product',
        ),
        migrations.AddField(
            model_name='productlocation',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='USERAPP.orders'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='column_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='row_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
