# Generated by Django 4.2.2 on 2023-09-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0009_userrole_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
