# Generated by Django 4.2.2 on 2023-09-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0010_alter_userrole_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='is_active',
        ),
    ]
