# Generated by Django 4.2.2 on 2023-09-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0011_remove_userrole_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
