# Generated by Django 4.2.2 on 2023-10-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0013_orders_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
