# Generated by Django 4.2.2 on 2023-10-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0015_product_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtype_name', models.CharField(max_length=100)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.producttype')),
            ],
        ),
    ]
