# Generated by Django 4.2.2 on 2023-10-11 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0016_brand_producttype_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtype',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.subtype'),
        ),
    ]
