# Generated by Django 4.2.2 on 2023-10-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0017_product_brand_product_product_type_product_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='brand',
        ),
        migrations.AddField(
            model_name='producttype',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='USERAPP.subcategory'),
        ),
    ]
