# Generated by Django 4.2.2 on 2024-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0021_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_inspected',
            field=models.BooleanField(default=False),
        ),
    ]
