# Generated by Django 4.2.2 on 2024-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0022_orders_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quality_check_status',
            field=models.CharField(choices=[('not_inspected', 'Not Inspected'), ('passed', 'Passed'), ('rejected', 'Rejected')], default='not_inspected', max_length=20),
        ),
    ]
