# Generated by Django 4.2.4 on 2023-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0002_remove_user_is_employee_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_legaladvisor',
            field=models.BooleanField(default=False, verbose_name='Is advisor'),
        ),
    ]
