# Generated by Django 4.2.4 on 2023-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0005_certificationapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_file', models.FileField(upload_to='certificates/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('expiry_date_from', models.DateField()),
                ('expiry_date_to', models.DateField()),
                ('certification_authority', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CertificationApplication',
        ),
    ]
