# Generated by Django 4.2.4 on 2023-09-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0010_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_names',
        ),
    ]
