# Generated by Django 4.2.4 on 2023-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0026_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='application',
        ),
        migrations.AddField(
            model_name='certification',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
