# Generated by Django 4.2.4 on 2023-09-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0027_remove_applicationstatus_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
    ]
