# Generated by Django 4.2.4 on 2023-09-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0028_product_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('total_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
