# Generated by Django 4.2.4 on 2023-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0031_productsummary_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='expiry_date_to',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='certification',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
