# Generated by Django 4.2.4 on 2023-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0034_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_item_images/'),
        ),
    ]
