# Generated by Django 4.2.4 on 2023-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0055_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='address',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
