# Generated by Django 4.2.4 on 2023-10-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0056_certification_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='certification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecohiveapp.certification'),
        ),
    ]
