# Generated by Django 4.2.2 on 2024-03-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0021_product_product_price'),
        ('ecohiveapp', '0060_remove_product_category_remove_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.supplier'),
        ),
    ]
