# Generated by Django 4.2.2 on 2024-03-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0061_alter_orderitem_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
